"""
agents.py — LangGraph multi-agent system for capital markets decision support.

Graph topology (linear pipeline):
    market_data → metrics → forecasting → sentiment → decision → risk → report → END

Each node receives the full MarketState, performs its task, and returns a
partial dict that LangGraph merges back into the shared state.

Usage:
    from agents import build_graph
    from data_loader import DEFAULT_TICKERS

    graph = build_graph()
    final_state = graph.invoke({
        "tickers": DEFAULT_TICKERS,
        "price_data": {}, "metrics": {}, "forecasts": {},
        "sentiment": {}, "decisions": {}, "risk_flags": {},
        "report": "", "timestamp": "",
    })
    print(final_state["report"])
"""

import json
import os
from datetime import datetime, timezone
from typing import TypedDict

from dotenv import load_dotenv
from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from langgraph.graph import END, StateGraph

from data_loader import DEFAULT_TICKERS, load_data
from forecasting import run_forecasting
from metrics import compute_metrics

# Load .env for local development (no-op on Streamlit Cloud)
load_dotenv()


def _get_api_key() -> str:
    """Return the OpenAI API key.

    Priority:
        1. st.secrets['OPENAI_API_KEY']  — Streamlit Cloud deployment
        2. OPENAI_API_KEY env var        — local .env or system environment
    """
    try:
        import streamlit as st
        return st.secrets["OPENAI_API_KEY"]
    except Exception:
        return os.getenv("OPENAI_API_KEY", "")


# ---------------------------------------------------------------------------
# Shared LLM client — initialised once at import time
# ---------------------------------------------------------------------------

# One shared client is used by all LLM-calling agents (sentiment + report).
# temperature=0.2 keeps responses focused and deterministic; higher values
# would make the model more creative but less consistent across runs.
_llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0.2,
    api_key=_get_api_key(),
)

# ---------------------------------------------------------------------------
# State schema
# ---------------------------------------------------------------------------


class MarketState(TypedDict):
    """Shared state threaded through every agent node in the capital markets graph.

    LangGraph passes this dict into every node function.  Each node returns a
    *partial* dict — only the keys it writes — and LangGraph merges those updates
    back into the shared state before passing it to the next node.

    Keys:
        tickers:    List of ticker symbols to analyse.
        price_data: Raw OHLCV DataFrames keyed by ticker symbol.
        metrics:    Nested dict {ticker: {metric_name: value}} from compute_metrics().
        forecasts:  Ticker → ML probability of positive next-week return (float 0-1).
        sentiment:  Ticker → LLM-classified label ("Bullish", "Neutral", or "Bearish").
        decisions:  Ticker → {"action": str, "score": int} from the decision rubric.
        risk_flags: Named risk warnings keyed by flag name (e.g. "concentration_risk").
        report:     200-word executive summary generated by the report agent.
        timestamp:  ISO-8601 UTC timestamp recorded when market data is first loaded.
    """

    tickers: list
    price_data: dict
    metrics: dict
    forecasts: dict
    sentiment: dict
    decisions: dict
    risk_flags: dict
    report: str
    timestamp: str


# ---------------------------------------------------------------------------
# Agent node functions
# ---------------------------------------------------------------------------


def market_data_agent(state: MarketState) -> dict:
    """Load daily OHLCV data for every ticker in state['tickers'].

    Calls load_data() from src/data_loader.py, which reads pre-downloaded CSVs
    from data/raw/.  Sets the pipeline timestamp here because this is the first
    node that touches real data.

    Returns:
        Partial state update: ``price_data`` and ``timestamp``.
    """
    print("[market_data_agent] Loading price data ...")

    # Fall back to the default ticker list if none were provided in state
    tickers = state.get("tickers") or DEFAULT_TICKERS

    # load_data() reads CSVs from data/raw/<TICKER>.csv into DataFrames.
    # Returns a dict: {"SPY": DataFrame, "QQQ": DataFrame, ...}
    price_data = load_data(tickers)

    # Record the wall-clock time the data was loaded so the report can cite it.
    # timezone.utc ensures the timestamp is unambiguous regardless of server locale.
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    print(f"  Loaded {len(price_data)} tickers.")

    # Returning only the keys we wrote; LangGraph merges this into the full state
    return {"price_data": price_data, "timestamp": timestamp}


def metrics_agent(state: MarketState) -> dict:
    """Compute financial performance metrics for all loaded tickers.

    Calls compute_metrics() from src/metrics.py and converts the resulting
    DataFrame to a nested dict {ticker: {metric_name: value}} so it is
    JSON-safe and easy for downstream agents to consume.

    Returns:
        Partial state update: ``metrics``.
    """
    print("[metrics_agent] Computing financial metrics ...")
    price_data = state.get("price_data", {})

    # Guard: if the previous node returned no data, skip cleanly
    if not price_data:
        print("  WARNING: price_data is empty — skipping metrics.")
        return {"metrics": {}}

    # compute_metrics() returns a DataFrame indexed by ticker with columns like
    # ann_return, ann_volatility, sharpe_ratio, max_drawdown, ma_50, ma_200, etc.
    metrics_df = compute_metrics(price_data)

    # orient='index' converts the DataFrame to:
    #   {"SPY": {"ann_return": 0.12, "sharpe_ratio": 0.8, ...}, "QQQ": {...}, ...}
    # This format is easier to look up by ticker in downstream agents than a
    # column-oriented dict, and it's plain Python so it serialises cleanly.
    metrics_dict = metrics_df.to_dict(orient="index")

    print(f"  Computed metrics for {len(metrics_dict)} tickers.")
    return {"metrics": metrics_dict}


def forecasting_agent(state: MarketState) -> dict:
    """Run per-ticker Random Forest models and record next-week return probabilities.

    Calls run_forecasting() from src/forecasting.py, which trains one model per
    ticker and (as a side effect) writes forecasting_probabilities.csv and
    forecasting_model_report.txt to data/processed/.

    Returns:
        Partial state update: ``forecasts``.
    """
    print("[forecasting_agent] Running ML forecasting models ...")
    price_data = state.get("price_data", {})

    if not price_data:
        print("  WARNING: price_data is empty — skipping forecasting.")
        return {"forecasts": {}}

    # run_forecasting() trains a Random Forest for each ticker on its OHLCV data,
    # evaluates on a held-out time window, and returns the model's estimated
    # probability that the next 5-day return will be positive.
    # Example return: {"SPY": 0.62, "QQQ": 0.48, "TLT": 0.31, ...}
    forecasts = run_forecasting(price_data)

    print(f"  Forecasts complete for {len(forecasts)} tickers.")
    return {"forecasts": forecasts}


def sentiment_agent(state: MarketState) -> dict:
    """Classify near-term market sentiment for each ticker using an OpenAI LLM.

    Builds a single batched prompt containing each ticker's key financial metrics
    and ML forecast probability, then asks the LLM to return a JSON dict mapping
    each ticker to Bullish / Neutral / Bearish.  Any ticker missing from the LLM
    response, or with an unrecognised label, defaults to "Neutral".

    Returns:
        Partial state update: ``sentiment``.
    """
    print("[sentiment_agent] Classifying sentiment via LLM ...")
    metrics = state.get("metrics", {})
    forecasts = state.get("forecasts", {})

    # If metrics are missing there's nothing meaningful to show the LLM —
    # default everything to Neutral so downstream agents still get a value
    if not metrics:
        print("  WARNING: metrics empty — defaulting all sentiment to Neutral.")
        return {"sentiment": {t: "Neutral" for t in state.get("price_data", {})}}

    # Build one compact line per ticker to include in the LLM prompt.
    # Batching all tickers into a single call is cheaper and faster than
    # making one API call per ticker (8 calls → 1 call).
    summaries = []
    for ticker, m in sorted(metrics.items()):
        prob = forecasts.get(ticker, float("nan"))
        # "prob == prob" is False only when prob is NaN (NaN != NaN by IEEE 754)
        prob_str = f"{prob:.1%}" if prob == prob else "n/a"
        summaries.append(
            f"  {ticker}: ann_return={m.get('ann_return', 0):.1%}, "
            f"volatility={m.get('ann_volatility', 0):.1%}, "
            f"sharpe={m.get('sharpe_ratio', 0):.2f}, "
            f"max_drawdown={m.get('max_drawdown', 0):.1%}, "
            f"forecast_prob={prob_str}"
        )

    # The prompt instructs the model to return pure JSON so we can parse it
    # reliably without any natural-language post-processing
    prompt = (
        "You are a senior equity analyst. Using only the quantitative data below, "
        "classify the near-term market sentiment for each ticker as exactly one of: "
        "Bullish, Neutral, or Bearish.\n\n"
        "Tickers:\n" + "\n".join(summaries) + "\n\n"
        "Respond with valid JSON only — a single object mapping each ticker symbol "
        'to its sentiment label. Example: {"SPY": "Bullish", "TLT": "Bearish"}'
    )

    try:
        # HumanMessage wraps the text in the chat format the API expects
        response = _llm.invoke([HumanMessage(content=prompt)])
        raw = response.content.strip()

        # Models sometimes wrap their JSON in ```json ... ``` fences even when
        # told not to — strip those before parsing
        if raw.startswith("```"):
            raw = raw.split("```")[1]       # take the content between the fences
            if raw.startswith("json"):
                raw = raw[4:]               # remove the language hint after ```

        parsed = json.loads(raw.strip())

        # Only accept the three valid labels; anything else becomes Neutral
        valid_labels = {"Bullish", "Neutral", "Bearish"}
        sentiment = {
            t: (v if v in valid_labels else "Neutral")
            for t, v in parsed.items()
        }

        # The LLM might omit a ticker — setdefault fills in Neutral for any gap
        for ticker in metrics:
            sentiment.setdefault(ticker, "Neutral")

    except Exception as exc:
        # If JSON parsing or the API call fails, fall back gracefully so the
        # rest of the pipeline can still produce a result
        print(f"  WARNING: LLM sentiment parsing failed ({exc}) — defaulting to Neutral.")
        sentiment = {t: "Neutral" for t in metrics}

    print(f"  Sentiment: {sentiment}")
    return {"sentiment": sentiment}


def decision_agent(state: MarketState) -> dict:
    """Score each ticker against a multi-factor rubric and assign a portfolio action.

    Scoring rubric (each criterion adds +1, max = 7):
        +1  Annualised return  > 10 %
        +1  Annualised volatility < 20 %
        +1  Sharpe ratio       > 0.5
        +1  Last close price is above the 200-day moving average
        +1  ML forecast probability of positive next-week return > 55 %
        +1  LLM sentiment classification is "Bullish"
        +1  Maximum drawdown > −25 % (loss less severe than a quarter of value)

    Score → Portfolio action:
        6–7  →  Overweight
        4–5  →  Neutral
        2–3  →  Underweight
        0–1  →  Avoid

    Returns:
        Partial state update: ``decisions`` — a dict {ticker: {"score": int, "action": str}}.
    """
    print("[decision_agent] Scoring tickers and assigning portfolio actions ...")
    metrics = state.get("metrics", {})
    forecasts = state.get("forecasts", {})
    sentiment = state.get("sentiment", {})

    decisions = {}

    for ticker, m in sorted(metrics.items()):
        score = 0

        # --- factor 1: strong positive trend ---
        if m.get("ann_return", 0) > 0.10:
            score += 1

        # --- factor 2: manageable risk (low vol = more predictable returns) ---
        if m.get("ann_volatility", 1.0) < 0.20:
            score += 1

        # --- factor 3: good risk-adjusted return ---
        if m.get("sharpe_ratio", 0) > 0.5:
            score += 1

        # --- factor 4: price momentum signal (above long-term trend = bullish) ---
        # Default ma_200 to infinity so the check fails safely if the MA is missing
        if m.get("last_close", 0) > m.get("ma_200", float("inf")):
            score += 1

        # --- factor 5: ML model says next week looks positive ---
        if forecasts.get(ticker, 0) > 0.55:
            score += 1

        # --- factor 6: LLM analyst agrees the outlook is positive ---
        if sentiment.get(ticker) == "Bullish":
            score += 1

        # --- factor 7: limited historical drawdown risk ---
        # max_drawdown is stored as a negative decimal (e.g. -0.32 = down 32%).
        # > -0.25 means the worst drop was less than 25%, which is the passing bar.
        if m.get("max_drawdown", -1.0) > -0.25:
            score += 1

        # Map total score to a portfolio action label
        if score >= 6:
            action = "Overweight"
        elif score >= 4:
            action = "Neutral"
        elif score >= 2:
            action = "Underweight"
        else:
            action = "Avoid"

        decisions[ticker] = {"score": score, "action": action}
        print(f"  {ticker}: score={score}/7 → {action}")

    return {"decisions": decisions}


def risk_agent(state: MarketState) -> dict:
    """Identify portfolio-level and ticker-level risk flags.

    Checks performed:
        Concentration risk — more than 3 tickers rated Overweight.  A highly
            concentrated overweight stance amplifies drawdown risk if the market
            turns.
        High volatility    — any ticker whose annualised volatility exceeds 30 %.
            These positions may behave unexpectedly under stress.

    Returns:
        Partial state update: ``risk_flags`` — a dict {flag_name: warning_message}.
        Empty dict if no flags are raised.
    """
    print("[risk_agent] Evaluating risk flags ...")
    decisions = state.get("decisions", {})
    metrics = state.get("metrics", {})
    risk_flags = {}

    # --- Concentration risk ---
    # Collect every ticker the decision agent rated as Overweight
    overweight = sorted(t for t, d in decisions.items() if d.get("action") == "Overweight")

    # More than 3 Overweight positions creates concentrated directional exposure —
    # if the market reverses, all positions move against the portfolio together
    if len(overweight) > 3:
        risk_flags["concentration_risk"] = (
            f"Concentration risk: {len(overweight)} tickers rated Overweight "
            f"({', '.join(overweight)}). Consider reducing broad overweight exposure."
        )
        print(f"  [!] {risk_flags['concentration_risk']}")

    # --- High volatility ---
    # A 30% annualised vol threshold is a common rule-of-thumb for "elevated risk"
    high_vol = sorted(t for t, m in metrics.items() if m.get("ann_volatility", 0) > 0.30)
    if high_vol:
        risk_flags["high_volatility"] = (
            f"High annualised volatility (>30%): {', '.join(high_vol)}. "
            "These positions carry elevated risk and may warrant tighter position sizing."
        )
        print(f"  [!] {risk_flags['high_volatility']}")

    if not risk_flags:
        print("  No risk flags raised.")

    return {"risk_flags": risk_flags}


def report_agent(state: MarketState) -> dict:
    """Generate a ~200-word executive summary using an OpenAI LLM.

    Synthesises portfolio actions, risk warnings, and key metrics into a concise
    narrative suitable for an investment committee briefing.  Falls back to a
    structured plain-text summary if the LLM call fails.

    Returns:
        Partial state update: ``report``.
    """
    print("[report_agent] Generating executive summary via LLM ...")

    decisions  = state.get("decisions", {})
    risk_flags = state.get("risk_flags", {})
    metrics    = state.get("metrics", {})
    forecasts  = state.get("forecasts", {})
    sentiment  = state.get("sentiment", {})
    timestamp  = state.get("timestamp", "")

    # Flatten each section of the state into readable plain-text lines so the
    # LLM receives structured context rather than raw nested dictionaries

    action_lines = "\n".join(
        f"  {t}: {d['action']} (score {d['score']}/7, sentiment {sentiment.get(t, 'N/A')})"
        for t, d in sorted(decisions.items())
    )

    # If there are no risk flags, tell the LLM explicitly — otherwise it might
    # hallucinate risks that don't exist
    risk_lines = (
        "\n".join(f"  - {msg}" for msg in risk_flags.values())
        if risk_flags
        else "  None identified."
    )

    metric_lines = "\n".join(
        f"  {t}: return={m.get('ann_return', 0):.1%}, "
        f"vol={m.get('ann_volatility', 0):.1%}, "
        f"sharpe={m.get('sharpe_ratio', 0):.2f}, "
        f"drawdown={m.get('max_drawdown', 0):.1%}, "
        f"forecast={forecasts.get(t, 0):.1%}"
        for t, m in sorted(metrics.items())
    )

    # The prompt gives the LLM a clear role, a word-count target, and explicit
    # topics to cover so the output is consistently structured
    prompt = (
        "You are a senior portfolio manager preparing an investment committee briefing. "
        "Write a concise executive summary of approximately 200 words based on the "
        "capital markets analysis below. Cover: overall market stance, the most important "
        "individual ticker recommendations, key risks to monitor, and the near-term outlook.\n\n"
        f"Analysis timestamp: {timestamp}\n\n"
        f"Portfolio Actions:\n{action_lines}\n\n"
        f"Risk Warnings:\n{risk_lines}\n\n"
        f"Key Metrics:\n{metric_lines}\n\n"
        "Write the executive summary (approximately 200 words):"
    )

    try:
        response = _llm.invoke([HumanMessage(content=prompt)])
        report = response.content.strip()
    except Exception as exc:
        # The fallback includes the raw structured data so downstream consumers
        # (e.g., the dashboard) still receive something useful even without the LLM
        report = (
            f"[LLM unavailable — {exc}]\n\n"
            f"Portfolio Actions:\n{action_lines}\n\n"
            f"Risk Warnings:\n{risk_lines}"
        )
        print(f"  WARNING: LLM report generation failed — {exc}")

    word_count = len(report.split())
    print(f"  Report generated ({word_count} words).")
    return {"report": report}


# ---------------------------------------------------------------------------
# Graph assembly
# ---------------------------------------------------------------------------


def build_graph():
    """Assemble and compile the capital markets LangGraph pipeline.

    Node execution order:
        market_data_agent → metrics_agent → forecasting_agent →
        sentiment_agent → decision_agent → risk_agent → report_agent → END

    Returns:
        A compiled LangGraph ``CompiledGraph`` ready to ``.invoke()`` with an
        initial MarketState dictionary.
    """
    # StateGraph takes the TypedDict class as its schema so LangGraph knows
    # which keys exist in the shared state and can validate updates
    builder = StateGraph(MarketState)

    # Register each agent function as a named node in the graph.
    # The string name is used when wiring edges below.
    builder.add_node("market_data_agent", market_data_agent)
    builder.add_node("metrics_agent", metrics_agent)
    builder.add_node("forecasting_agent", forecasting_agent)
    builder.add_node("sentiment_agent", sentiment_agent)
    builder.add_node("decision_agent", decision_agent)
    builder.add_node("risk_agent", risk_agent)
    builder.add_node("report_agent", report_agent)

    # set_entry_point marks where execution begins when .invoke() is called
    builder.set_entry_point("market_data_agent")

    # add_edge defines the execution order: after node A finishes, run node B.
    # This creates a strict linear pipeline — no branching or parallelism here.
    builder.add_edge("market_data_agent", "metrics_agent")
    builder.add_edge("metrics_agent", "forecasting_agent")
    builder.add_edge("forecasting_agent", "sentiment_agent")
    builder.add_edge("sentiment_agent", "decision_agent")
    builder.add_edge("decision_agent", "risk_agent")
    builder.add_edge("risk_agent", "report_agent")

    # END is LangGraph's sentinel value signalling that the graph is finished.
    # After report_agent runs, the compiled graph returns the final state.
    builder.add_edge("report_agent", END)

    # compile() validates the graph structure (no orphan nodes, reachable END,
    # etc.) and returns an executable object with .invoke() / .stream() methods
    return builder.compile()


# ---------------------------------------------------------------------------
# Module smoke-test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    graph = build_graph()

    initial_state: MarketState = {
        "tickers": DEFAULT_TICKERS,
        # All other keys start empty; each agent fills in its own section
        "price_data": {},
        "metrics": {},
        "forecasts": {},
        "sentiment": {},
        "decisions": {},
        "risk_flags": {},
        "report": "",
        "timestamp": "",
    }

    final_state = graph.invoke(initial_state)

    print("\n" + "=" * 60)
    print("EXECUTIVE SUMMARY")
    print("=" * 60)
    print(final_state["report"])

    print("\n--- Portfolio Decisions ---")
    for ticker, d in sorted(final_state["decisions"].items()):
        sentiment_label = final_state["sentiment"].get(ticker, "N/A")
        print(f"  {ticker:<6} {d['action']:<12} score={d['score']}/7  sentiment={sentiment_label}")

    if final_state["risk_flags"]:
        print("\n--- Risk Flags ---")
        for flag, msg in final_state["risk_flags"].items():
            print(f"  [{flag}] {msg}")
